=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::MediaSettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::MediaSettings do
  let(:instance) { OpenapiClient::MediaSettings.new }

  describe 'test an instance of MediaSettings' do
    it 'should create an instance of MediaSettings' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::MediaSettings)
    end
  end

  describe 'test attribute "auto_download"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["image", "audio", "voice", "video", "document", "sticker"])
      # validator.allowable_values.each do |value|
      #   expect { instance.auto_download = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "init_avatars"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
