---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/requests":
    get:
      summary: Retrieves all requests
      tags:
      - Requests
      responses:
        '200':
          description: requests#index
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3001
