---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/requests":
    get:
      summary: Retrieves all requests
      tags:
      - Requests
      responses:
        '200':
          description: requests#index
    post:
      summary: Creates a request
      tags:
      - Requests
      parameters: []
      responses:
        '201':
          description: request#create
          content:
            application/json:
              schema:
                type: object
                properties:
                  request:
                    type: object
                    properties:
                      id:
                        type: integer
                      user_phone:
                        type: string
                      user_name:
                        type: string
                      user_email:
                        type: string
                      part_name:
                        type: string
                      part_brand:
                        type: string
                      part_model:
                        type: string
                      part_year:
                        type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: object
                  properties:
                    user_phone:
                      type: string
                    user_name:
                      type: string
                    user_email:
                      type: string
                    part_name:
                      type: string
                    part_brand:
                      type: string
                    part_model:
                      type: string
                    part_year:
                      type: integer
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3001
