---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/requests":
    get:
      summary: Retrieves a filtered list requests
      tags:
      - Requests
      responses:
        '200':
          description: requests#index
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    request:
                      type: object
                      properties:
                        part_name:
                          type: string
                        part_brand:
                          type: string
                        part_model:
                          type: string
                        part_year:
                          type: integer
                        part_image:
                          type: string
                        part_chassis:
                          type: string
                        show_key:
                          type: string
                        created_at:
                          type: string
                        state:
                          type: number
                        pending_data:
                          type: array
                          items:
                            type: string
      parameters:
      - name: q[user_phone_eq]
        in: query
        description: Search by phone number
        required: false
        schema:
          type: string
      - name: q[part_brand_cont]
        in: query
        description: Search by part brand
        required: false
        schema:
          type: string
      - name: q[part_model_cont]
        in: query
        description: Search by part model
        required: false
        schema:
          type: string
      - name: q[part_year_eq]
        in: query
        description: Search by part year
        required: false
        schema:
          type: integer
    post:
      summary: Creates a request
      tags:
      - Requests
      parameters: []
      responses:
        '201':
          description: request#create
          content:
            application/json:
              schema:
                type: object
                properties:
                  request:
                    type: object
                    properties:
                      part_name:
                        type: string
                      part_brand:
                        type: string
                      part_model:
                        type: string
                      part_year:
                        type: integer
                      part_image:
                        type: string
                      part_chassis:
                        type: string
                      show_key:
                        type: string
                      created_at:
                        type: string
                      state:
                        type: number
                      pending_data:
                        type: array
                        items:
                          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: object
                  properties:
                    user_phone:
                      type: string
                    user_name:
                      type: string
                    user_email:
                      type: string
                    part_name:
                      type: string
                    part_brand:
                      type: string
                    part_model:
                      type: string
                    part_year:
                      type: integer
                    part_image:
                      type: string
  "/api/v1/requests/{id}":
    get:
      summary: Retrieves a request
      tags:
      - Requests
      parameters:
      - name: id
        in: path
        description: Request ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: request#show
          content:
            application/json:
              schema:
                type: object
                properties:
                  request:
                    type: object
                    properties:
                      part_name:
                        type: string
                      part_brand:
                        type: string
                      part_model:
                        type: string
                      part_year:
                        type: integer
                      part_image:
                        type: string
                      part_chassis:
                        type: string
                      show_key:
                        type: string
                      created_at:
                        type: string
                      state:
                        type: number
                      pending_data:
                        type: array
                        items:
                          type: string
    put:
      summary: Updates a request
      tags:
      - Requests
      parameters:
      - name: id
        in: path
        description: Request ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: request#update
          content:
            application/json:
              schema:
                type: object
                properties:
                  request:
                    type: object
                    properties:
                      part_name:
                        type: string
                      part_brand:
                        type: string
                      part_model:
                        type: string
                      part_year:
                        type: integer
                      part_image:
                        type: string
                      part_chassis:
                        type: string
                      show_key:
                        type: string
                      created_at:
                        type: string
                      state:
                        type: number
                      pending_data:
                        type: array
                        items:
                          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: object
                  properties:
                    user_phone:
                      type: string
                    user_name:
                      type: string
                    user_email:
                      type: string
                    part_name:
                      type: string
                    part_brand:
                      type: string
                    part_model:
                      type: string
                    part_year:
                      type: integer
                    part_image:
                      type: string
    delete:
      summary: Deletes a request
      tags:
      - Requests
      parameters:
      - name: id
        in: path
        description: Request ID
        required: true
        schema:
          type: string
      responses:
        '204':
          description: request#destroy
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3001
