=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module OpenapiClient
  class Currency
    USD = "USD".freeze
    EUR = "EUR".freeze
    AED = "AED".freeze
    AFN = "AFN".freeze
    ALL = "ALL".freeze
    AMD = "AMD".freeze
    ANG = "ANG".freeze
    AOA = "AOA".freeze
    ARS = "ARS".freeze
    AUD = "AUD".freeze
    AWG = "AWG".freeze
    AZN = "AZN".freeze
    BAM = "BAM".freeze
    BBD = "BBD".freeze
    BDT = "BDT".freeze
    BGN = "BGN".freeze
    BHD = "BHD".freeze
    BIF = "BIF".freeze
    BMD = "BMD".freeze
    BND = "BND".freeze
    BOB = "BOB".freeze
    BRL = "BRL".freeze
    BSD = "BSD".freeze
    BTN = "BTN".freeze
    BWP = "BWP".freeze
    BYN = "BYN".freeze
    BZD = "BZD".freeze
    CAD = "CAD".freeze
    CDF = "CDF".freeze
    CHF = "CHF".freeze
    CLP = "CLP".freeze
    CNY = "CNY".freeze
    COP = "COP".freeze
    CRC = "CRC".freeze
    CUP = "CUP".freeze
    CVE = "CVE".freeze
    CZK = "CZK".freeze
    DJF = "DJF".freeze
    DKK = "DKK".freeze
    DOP = "DOP".freeze
    DZD = "DZD".freeze
    EGP = "EGP".freeze
    ERN = "ERN".freeze
    ETB = "ETB".freeze
    FJD = "FJD".freeze
    FKP = "FKP".freeze
    GBP = "GBP".freeze
    GEL = "GEL".freeze
    GGP = "GGP".freeze
    GHS = "GHS".freeze
    GIP = "GIP".freeze
    GMD = "GMD".freeze
    GNF = "GNF".freeze
    GTQ = "GTQ".freeze
    GYD = "GYD".freeze
    HKD = "HKD".freeze
    HNL = "HNL".freeze
    HRK = "HRK".freeze
    HTG = "HTG".freeze
    HUF = "HUF".freeze
    IDR = "IDR".freeze
    ILS = "ILS".freeze
    IMP = "IMP".freeze
    INR = "INR".freeze
    IQD = "IQD".freeze
    IRR = "IRR".freeze
    ISK = "ISK".freeze
    JEP = "JEP".freeze
    JMD = "JMD".freeze
    JOD = "JOD".freeze
    JPY = "JPY".freeze
    KES = "KES".freeze
    KGS = "KGS".freeze
    KHR = "KHR".freeze
    KMF = "KMF".freeze
    KPW = "KPW".freeze
    KRW = "KRW".freeze
    KWD = "KWD".freeze
    KYD = "KYD".freeze
    KZT = "KZT".freeze
    LAK = "LAK".freeze
    LBP = "LBP".freeze
    LKR = "LKR".freeze
    LRD = "LRD".freeze
    LSL = "LSL".freeze
    LYD = "LYD".freeze
    MAD = "MAD".freeze
    MDL = "MDL".freeze
    MGA = "MGA".freeze
    MKD = "MKD".freeze
    MMK = "MMK".freeze
    MNT = "MNT".freeze
    MOP = "MOP".freeze
    MRU = "MRU".freeze
    MUR = "MUR".freeze
    MVR = "MVR".freeze
    MWK = "MWK".freeze
    MXN = "MXN".freeze
    MYR = "MYR".freeze
    MZN = "MZN".freeze
    NAD = "NAD".freeze
    NGN = "NGN".freeze
    NIO = "NIO".freeze
    NOK = "NOK".freeze
    NPR = "NPR".freeze
    NZD = "NZD".freeze
    OMR = "OMR".freeze
    PAB = "PAB".freeze
    PEN = "PEN".freeze
    PGK = "PGK".freeze
    PHP = "PHP".freeze
    PKR = "PKR".freeze
    PLN = "PLN".freeze
    PYG = "PYG".freeze
    QAR = "QAR".freeze
    RON = "RON".freeze
    RSD = "RSD".freeze
    RUB = "RUB".freeze
    RWF = "RWF".freeze
    SAR = "SAR".freeze
    SBD = "SBD".freeze
    SCR = "SCR".freeze
    SDG = "SDG".freeze
    SEK = "SEK".freeze
    SGD = "SGD".freeze
    SHP = "SHP".freeze
    SLL = "SLL".freeze
    SOS = "SOS".freeze
    SRD = "SRD".freeze
    SSP = "SSP".freeze
    STN = "STN".freeze
    SVC = "SVC".freeze
    SYP = "SYP".freeze
    SZL = "SZL".freeze
    THB = "THB".freeze
    TJS = "TJS".freeze
    TMT = "TMT".freeze
    TND = "TND".freeze
    TOP = "TOP".freeze
    TRY = "TRY".freeze
    TTD = "TTD".freeze
    TWD = "TWD".freeze
    TZS = "TZS".freeze
    UAH = "UAH".freeze
    UGX = "UGX".freeze
    UYU = "UYU".freeze
    UZS = "UZS".freeze
    VEF = "VEF".freeze
    VND = "VND".freeze
    VUV = "VUV".freeze
    WST = "WST".freeze
    XAF = "XAF".freeze
    XCD = "XCD".freeze
    XOF = "XOF".freeze
    XPF = "XPF".freeze
    YER = "YER".freeze
    ZAR = "ZAR".freeze
    ZMW = "ZMW".freeze
    ZWL = "ZWL".freeze

    def self.all_vars
      @all_vars ||= [USD, EUR, AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, BOB, BRL, BSD, BTN, BWP, BYN, BZD, CAD, CDF, CHF, CLP, CNY, COP, CRC, CUP, CVE, CZK, DJF, DKK, DOP, DZD, EGP, ERN, ETB, FJD, FKP, GBP, GEL, GGP, GHS, GIP, GMD, GNF, GTQ, GYD, HKD, HNL, HRK, HTG, HUF, IDR, ILS, IMP, INR, IQD, IRR, ISK, JEP, JMD, JOD, JPY, KES, KGS, KHR, KMF, KPW, KRW, KWD, KYD, KZT, LAK, LBP, LKR, LRD, LSL, LYD, MAD, MDL, MGA, MKD, MMK, MNT, MOP, MRU, MUR, MVR, MWK, MXN, MYR, MZN, NAD, NGN, NIO, NOK, NPR, NZD, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PYG, QAR, RON, RSD, RUB, RWF, SAR, SBD, SCR, SDG, SEK, SGD, SHP, SLL, SOS, SRD, SSP, STN, SVC, SYP, SZL, THB, TJS, TMT, TND, TOP, TRY, TTD, TWD, TZS, UAH, UGX, UYU, UZS, VEF, VND, VUV, WST, XAF, XCD, XOF, XPF, YER, ZAR, ZMW, ZWL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Currency.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Currency"
    end
  end
end
