=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module OpenapiClient
  class Group
    # Chat ID
    attr_accessor :id

    # Group name
    attr_accessor :name

    # Chat type
    attr_accessor :type

    # Chat timestamp
    attr_accessor :timestamp

    # Chat picture URL
    attr_accessor :chat_pic

    # Chat full picture URL
    attr_accessor :chat_pic_full

    # Is chat pinned
    attr_accessor :pin

    # Is chat muted
    attr_accessor :mute

    # Chat mute until
    attr_accessor :mute_until

    # Is chat archived
    attr_accessor :archive

    # Unread messages count
    attr_accessor :unread

    # Is chat unread mention
    attr_accessor :unread_mention

    # Is chat read only
    attr_accessor :read_only

    # Is chat not spam
    attr_accessor :not_spam

    attr_accessor :last_message

    # Labels associated with chat
    attr_accessor :labels

    # Group name owner
    attr_accessor :name_owner

    # Group name change timestamp
    attr_accessor :name_at

    # Group description
    attr_accessor :description

    # Group description owner
    attr_accessor :description_owner

    # Group description ID
    attr_accessor :description_id

    # Group size
    attr_accessor :size

    # Group participants
    attr_accessor :participants

    # Group creation timestamp
    attr_accessor :created_at

    # Contact ID
    attr_accessor :created_by

    # Is group suspended
    attr_accessor :suspended

    # Is group terminated
    attr_accessor :terminated

    # Is group parent
    attr_accessor :is_parent

    # Is group default subgroup
    attr_accessor :is_default_subgroup

    # If only admins can change group settings
    attr_accessor :restricted

    # If only admins can send messages
    attr_accessor :announcements

    # If only admins can add members
    attr_accessor :admin_add_member_mode

    # Group ephemeral timer
    attr_accessor :ephemeral

    # Group invite code
    attr_accessor :invite_code

    # If group is community announce
    attr_accessor :is_community_announce

    # Chat ID
    attr_accessor :linked_parent

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'type' => :'type',
        :'timestamp' => :'timestamp',
        :'chat_pic' => :'chat_pic',
        :'chat_pic_full' => :'chat_pic_full',
        :'pin' => :'pin',
        :'mute' => :'mute',
        :'mute_until' => :'mute_until',
        :'archive' => :'archive',
        :'unread' => :'unread',
        :'unread_mention' => :'unread_mention',
        :'read_only' => :'read_only',
        :'not_spam' => :'not_spam',
        :'last_message' => :'last_message',
        :'labels' => :'labels',
        :'name_owner' => :'name_owner',
        :'name_at' => :'name_at',
        :'description' => :'description',
        :'description_owner' => :'description_owner',
        :'description_id' => :'description_id',
        :'size' => :'size',
        :'participants' => :'participants',
        :'created_at' => :'created_at',
        :'created_by' => :'created_by',
        :'suspended' => :'suspended',
        :'terminated' => :'terminated',
        :'is_parent' => :'is_parent',
        :'is_default_subgroup' => :'is_default_subgroup',
        :'restricted' => :'restricted',
        :'announcements' => :'announcements',
        :'admin_add_member_mode' => :'adminAddMemberMode',
        :'ephemeral' => :'ephemeral',
        :'invite_code' => :'invite_code',
        :'is_community_announce' => :'isCommunityAnnounce',
        :'linked_parent' => :'linkedParent'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'type' => :'String',
        :'timestamp' => :'Integer',
        :'chat_pic' => :'String',
        :'chat_pic_full' => :'String',
        :'pin' => :'Boolean',
        :'mute' => :'Boolean',
        :'mute_until' => :'Integer',
        :'archive' => :'Boolean',
        :'unread' => :'Integer',
        :'unread_mention' => :'Boolean',
        :'read_only' => :'Boolean',
        :'not_spam' => :'Boolean',
        :'last_message' => :'Message',
        :'labels' => :'Array<Label>',
        :'name_owner' => :'String',
        :'name_at' => :'Integer',
        :'description' => :'String',
        :'description_owner' => :'String',
        :'description_id' => :'String',
        :'size' => :'Integer',
        :'participants' => :'Array<Participant>',
        :'created_at' => :'Integer',
        :'created_by' => :'String',
        :'suspended' => :'Boolean',
        :'terminated' => :'Boolean',
        :'is_parent' => :'Boolean',
        :'is_default_subgroup' => :'Boolean',
        :'restricted' => :'Boolean',
        :'announcements' => :'Boolean',
        :'admin_add_member_mode' => :'Boolean',
        :'ephemeral' => :'Float',
        :'invite_code' => :'String',
        :'is_community_announce' => :'Boolean',
        :'linked_parent' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'Chat'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::Group` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::Group`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      end

      if attributes.key?(:'chat_pic')
        self.chat_pic = attributes[:'chat_pic']
      end

      if attributes.key?(:'chat_pic_full')
        self.chat_pic_full = attributes[:'chat_pic_full']
      end

      if attributes.key?(:'pin')
        self.pin = attributes[:'pin']
      end

      if attributes.key?(:'mute')
        self.mute = attributes[:'mute']
      end

      if attributes.key?(:'mute_until')
        self.mute_until = attributes[:'mute_until']
      end

      if attributes.key?(:'archive')
        self.archive = attributes[:'archive']
      end

      if attributes.key?(:'unread')
        self.unread = attributes[:'unread']
      end

      if attributes.key?(:'unread_mention')
        self.unread_mention = attributes[:'unread_mention']
      end

      if attributes.key?(:'read_only')
        self.read_only = attributes[:'read_only']
      end

      if attributes.key?(:'not_spam')
        self.not_spam = attributes[:'not_spam']
      end

      if attributes.key?(:'last_message')
        self.last_message = attributes[:'last_message']
      end

      if attributes.key?(:'labels')
        if (value = attributes[:'labels']).is_a?(Array)
          self.labels = value
        end
      end

      if attributes.key?(:'name_owner')
        self.name_owner = attributes[:'name_owner']
      end

      if attributes.key?(:'name_at')
        self.name_at = attributes[:'name_at']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'description_owner')
        self.description_owner = attributes[:'description_owner']
      end

      if attributes.key?(:'description_id')
        self.description_id = attributes[:'description_id']
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      else
        self.size = nil
      end

      if attributes.key?(:'participants')
        if (value = attributes[:'participants']).is_a?(Array)
          self.participants = value
        end
      else
        self.participants = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'suspended')
        self.suspended = attributes[:'suspended']
      end

      if attributes.key?(:'terminated')
        self.terminated = attributes[:'terminated']
      end

      if attributes.key?(:'is_parent')
        self.is_parent = attributes[:'is_parent']
      end

      if attributes.key?(:'is_default_subgroup')
        self.is_default_subgroup = attributes[:'is_default_subgroup']
      end

      if attributes.key?(:'restricted')
        self.restricted = attributes[:'restricted']
      end

      if attributes.key?(:'announcements')
        self.announcements = attributes[:'announcements']
      end

      if attributes.key?(:'admin_add_member_mode')
        self.admin_add_member_mode = attributes[:'admin_add_member_mode']
      end

      if attributes.key?(:'ephemeral')
        self.ephemeral = attributes[:'ephemeral']
      end

      if attributes.key?(:'invite_code')
        self.invite_code = attributes[:'invite_code']
      end

      if attributes.key?(:'is_community_announce')
        self.is_community_announce = attributes[:'is_community_announce']
      end

      if attributes.key?(:'linked_parent')
        self.linked_parent = attributes[:'linked_parent']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      pattern = Regexp.new(/^[\d-]{10,31}@[\w\.]{1,}$/)
      if @id !~ pattern
        invalid_properties.push("invalid value for \"id\", must conform to the pattern #{pattern}.")
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @size.nil?
        invalid_properties.push('invalid value for "size", size cannot be nil.')
      end

      if @participants.nil?
        invalid_properties.push('invalid value for "participants", participants cannot be nil.')
      end

      pattern = Regexp.new(/^([\d]{7,15})?$/)
      if !@created_by.nil? && @created_by !~ pattern
        invalid_properties.push("invalid value for \"created_by\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^[\d-]{10,31}@[\w\.]{1,}$/)
      if !@linked_parent.nil? && @linked_parent !~ pattern
        invalid_properties.push("invalid value for \"linked_parent\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @id !~ Regexp.new(/^[\d-]{10,31}@[\w\.]{1,}$/)
      return false if @name.nil?
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["group", "contact", "broadcast", "newsletter", "unknown"])
      return false unless type_validator.valid?(@type)
      return false if @size.nil?
      return false if @participants.nil?
      return false if !@created_by.nil? && @created_by !~ Regexp.new(/^([\d]{7,15})?$/)
      return false if !@linked_parent.nil? && @linked_parent !~ Regexp.new(/^[\d-]{10,31}@[\w\.]{1,}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      pattern = Regexp.new(/^[\d-]{10,31}@[\w\.]{1,}$/)
      if id !~ pattern
        fail ArgumentError, "invalid value for \"id\", must conform to the pattern #{pattern}."
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["group", "contact", "broadcast", "newsletter", "unknown"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] size Value to be assigned
    def size=(size)
      if size.nil?
        fail ArgumentError, 'size cannot be nil'
      end

      @size = size
    end

    # Custom attribute writer method with validation
    # @param [Object] participants Value to be assigned
    def participants=(participants)
      if participants.nil?
        fail ArgumentError, 'participants cannot be nil'
      end

      @participants = participants
    end

    # Custom attribute writer method with validation
    # @param [Object] created_by Value to be assigned
    def created_by=(created_by)
      if created_by.nil?
        fail ArgumentError, 'created_by cannot be nil'
      end

      pattern = Regexp.new(/^([\d]{7,15})?$/)
      if created_by !~ pattern
        fail ArgumentError, "invalid value for \"created_by\", must conform to the pattern #{pattern}."
      end

      @created_by = created_by
    end

    # Custom attribute writer method with validation
    # @param [Object] linked_parent Value to be assigned
    def linked_parent=(linked_parent)
      if linked_parent.nil?
        fail ArgumentError, 'linked_parent cannot be nil'
      end

      pattern = Regexp.new(/^[\d-]{10,31}@[\w\.]{1,}$/)
      if linked_parent !~ pattern
        fail ArgumentError, "invalid value for \"linked_parent\", must conform to the pattern #{pattern}."
      end

      @linked_parent = linked_parent
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          type == o.type &&
          timestamp == o.timestamp &&
          chat_pic == o.chat_pic &&
          chat_pic_full == o.chat_pic_full &&
          pin == o.pin &&
          mute == o.mute &&
          mute_until == o.mute_until &&
          archive == o.archive &&
          unread == o.unread &&
          unread_mention == o.unread_mention &&
          read_only == o.read_only &&
          not_spam == o.not_spam &&
          last_message == o.last_message &&
          labels == o.labels &&
          name_owner == o.name_owner &&
          name_at == o.name_at &&
          description == o.description &&
          description_owner == o.description_owner &&
          description_id == o.description_id &&
          size == o.size &&
          participants == o.participants &&
          created_at == o.created_at &&
          created_by == o.created_by &&
          suspended == o.suspended &&
          terminated == o.terminated &&
          is_parent == o.is_parent &&
          is_default_subgroup == o.is_default_subgroup &&
          restricted == o.restricted &&
          announcements == o.announcements &&
          admin_add_member_mode == o.admin_add_member_mode &&
          ephemeral == o.ephemeral &&
          invite_code == o.invite_code &&
          is_community_announce == o.is_community_announce &&
          linked_parent == o.linked_parent
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, type, timestamp, chat_pic, chat_pic_full, pin, mute, mute_until, archive, unread, unread_mention, read_only, not_spam, last_message, labels, name_owner, name_at, description, description_owner, description_id, size, participants, created_at, created_by, suspended, terminated, is_parent, is_default_subgroup, restricted, announcements, admin_add_member_mode, ephemeral, invite_code, is_community_announce, linked_parent].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
