=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module OpenapiClient
  class Message
    # Message ID
    attr_accessor :id

    attr_accessor :type

    # Message subtype
    attr_accessor :subtype

    # Chat ID
    attr_accessor :chat_id

    # Chat name
    attr_accessor :chat_name

    # WhatsApp ID of the sender
    attr_accessor :from

    # Is message from me
    attr_accessor :from_me

    # Pushname of the sender
    attr_accessor :from_name

    attr_accessor :source

    # Message timestamp
    attr_accessor :timestamp

    # Device ID, if the message was not sent through the app
    attr_accessor :device_id

    attr_accessor :status

    attr_accessor :text

    attr_accessor :image

    attr_accessor :video

    attr_accessor :short

    attr_accessor :gif

    attr_accessor :audio

    attr_accessor :voice

    attr_accessor :document

    attr_accessor :link_preview

    attr_accessor :sticker

    attr_accessor :location

    attr_accessor :live_location

    attr_accessor :contact

    attr_accessor :contact_list

    attr_accessor :interactive

    attr_accessor :poll

    attr_accessor :hsm

    attr_accessor :system

    attr_accessor :order

    attr_accessor :group_invite

    attr_accessor :newsletter_invite

    attr_accessor :admin_invite

    attr_accessor :product

    attr_accessor :catalog

    attr_accessor :product_items

    attr_accessor :action

    attr_accessor :context

    attr_accessor :event

    attr_accessor :list

    attr_accessor :buttons

    # Reactions for message
    attr_accessor :reactions

    # Labels associated with message
    attr_accessor :labels

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'type' => :'type',
        :'subtype' => :'subtype',
        :'chat_id' => :'chat_id',
        :'chat_name' => :'chat_name',
        :'from' => :'from',
        :'from_me' => :'from_me',
        :'from_name' => :'from_name',
        :'source' => :'source',
        :'timestamp' => :'timestamp',
        :'device_id' => :'device_id',
        :'status' => :'status',
        :'text' => :'text',
        :'image' => :'image',
        :'video' => :'video',
        :'short' => :'short',
        :'gif' => :'gif',
        :'audio' => :'audio',
        :'voice' => :'voice',
        :'document' => :'document',
        :'link_preview' => :'link_preview',
        :'sticker' => :'sticker',
        :'location' => :'location',
        :'live_location' => :'live_location',
        :'contact' => :'contact',
        :'contact_list' => :'contact_list',
        :'interactive' => :'interactive',
        :'poll' => :'poll',
        :'hsm' => :'hsm',
        :'system' => :'system',
        :'order' => :'order',
        :'group_invite' => :'group_invite',
        :'newsletter_invite' => :'newsletter_invite',
        :'admin_invite' => :'admin_invite',
        :'product' => :'product',
        :'catalog' => :'catalog',
        :'product_items' => :'product_items',
        :'action' => :'action',
        :'context' => :'context',
        :'event' => :'event',
        :'list' => :'list',
        :'buttons' => :'buttons',
        :'reactions' => :'reactions',
        :'labels' => :'labels'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'type' => :'MessageType',
        :'subtype' => :'String',
        :'chat_id' => :'String',
        :'chat_name' => :'String',
        :'from' => :'String',
        :'from_me' => :'Boolean',
        :'from_name' => :'String',
        :'source' => :'MessageSource',
        :'timestamp' => :'Float',
        :'device_id' => :'Float',
        :'status' => :'StatusEnum',
        :'text' => :'MessageContentText',
        :'image' => :'MessageContentImage',
        :'video' => :'MessageContentVideo',
        :'short' => :'MessageContentVideo',
        :'gif' => :'MessageContentVideo',
        :'audio' => :'MessageContentAudio',
        :'voice' => :'MessageContentAudio',
        :'document' => :'MessageContentDocument',
        :'link_preview' => :'MessageContentLinkPreview',
        :'sticker' => :'MessageContentSticker',
        :'location' => :'MessageContentLocation',
        :'live_location' => :'MessageContentLiveLocation',
        :'contact' => :'MessageContentContact',
        :'contact_list' => :'MessageContentContacts',
        :'interactive' => :'MessageContentInteractive',
        :'poll' => :'MessageContentPoll',
        :'hsm' => :'MessageContentHSM',
        :'system' => :'MessageContentSystem',
        :'order' => :'MessageContentOrder',
        :'group_invite' => :'MessageContentLinkPreview',
        :'newsletter_invite' => :'MessageContentLinkPreview',
        :'admin_invite' => :'MessageContentNewsletterAdminInvite',
        :'product' => :'MessageContentProduct',
        :'catalog' => :'MessageContentLinkPreview',
        :'product_items' => :'MessageContentProductItems',
        :'action' => :'MessageAction',
        :'context' => :'MessageContext',
        :'event' => :'MessageContentEvent',
        :'list' => :'MessageContentList',
        :'buttons' => :'MessageContentButtons',
        :'reactions' => :'Array<MessageReaction>',
        :'labels' => :'Array<Label>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::Message` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::Message`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = 'text'
      end

      if attributes.key?(:'subtype')
        self.subtype = attributes[:'subtype']
      end

      if attributes.key?(:'chat_id')
        self.chat_id = attributes[:'chat_id']
      else
        self.chat_id = nil
      end

      if attributes.key?(:'chat_name')
        self.chat_name = attributes[:'chat_name']
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      end

      if attributes.key?(:'from_me')
        self.from_me = attributes[:'from_me']
      else
        self.from_me = nil
      end

      if attributes.key?(:'from_name')
        self.from_name = attributes[:'from_name']
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      else
        self.source = 'text'
      end

      if attributes.key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      else
        self.timestamp = nil
      end

      if attributes.key?(:'device_id')
        self.device_id = attributes[:'device_id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'text')
        self.text = attributes[:'text']
      end

      if attributes.key?(:'image')
        self.image = attributes[:'image']
      end

      if attributes.key?(:'video')
        self.video = attributes[:'video']
      end

      if attributes.key?(:'short')
        self.short = attributes[:'short']
      end

      if attributes.key?(:'gif')
        self.gif = attributes[:'gif']
      end

      if attributes.key?(:'audio')
        self.audio = attributes[:'audio']
      end

      if attributes.key?(:'voice')
        self.voice = attributes[:'voice']
      end

      if attributes.key?(:'document')
        self.document = attributes[:'document']
      end

      if attributes.key?(:'link_preview')
        self.link_preview = attributes[:'link_preview']
      end

      if attributes.key?(:'sticker')
        self.sticker = attributes[:'sticker']
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'live_location')
        self.live_location = attributes[:'live_location']
      end

      if attributes.key?(:'contact')
        self.contact = attributes[:'contact']
      end

      if attributes.key?(:'contact_list')
        self.contact_list = attributes[:'contact_list']
      end

      if attributes.key?(:'interactive')
        self.interactive = attributes[:'interactive']
      end

      if attributes.key?(:'poll')
        self.poll = attributes[:'poll']
      end

      if attributes.key?(:'hsm')
        self.hsm = attributes[:'hsm']
      end

      if attributes.key?(:'system')
        self.system = attributes[:'system']
      end

      if attributes.key?(:'order')
        self.order = attributes[:'order']
      end

      if attributes.key?(:'group_invite')
        self.group_invite = attributes[:'group_invite']
      end

      if attributes.key?(:'newsletter_invite')
        self.newsletter_invite = attributes[:'newsletter_invite']
      end

      if attributes.key?(:'admin_invite')
        self.admin_invite = attributes[:'admin_invite']
      end

      if attributes.key?(:'product')
        self.product = attributes[:'product']
      end

      if attributes.key?(:'catalog')
        self.catalog = attributes[:'catalog']
      end

      if attributes.key?(:'product_items')
        self.product_items = attributes[:'product_items']
      end

      if attributes.key?(:'action')
        self.action = attributes[:'action']
      end

      if attributes.key?(:'context')
        self.context = attributes[:'context']
      end

      if attributes.key?(:'event')
        self.event = attributes[:'event']
      end

      if attributes.key?(:'list')
        self.list = attributes[:'list']
      end

      if attributes.key?(:'buttons')
        self.buttons = attributes[:'buttons']
      end

      if attributes.key?(:'reactions')
        if (value = attributes[:'reactions']).is_a?(Array)
          self.reactions = value
        end
      end

      if attributes.key?(:'labels')
        if (value = attributes[:'labels']).is_a?(Array)
          self.labels = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @chat_id.nil?
        invalid_properties.push('invalid value for "chat_id", chat_id cannot be nil.')
      end

      if @from_me.nil?
        invalid_properties.push('invalid value for "from_me", from_me cannot be nil.')
      end

      if @timestamp.nil?
        invalid_properties.push('invalid value for "timestamp", timestamp cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @type.nil?
      return false if @chat_id.nil?
      return false if @from_me.nil?
      return false if @timestamp.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if type.nil?
        fail ArgumentError, 'type cannot be nil'
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] chat_id Value to be assigned
    def chat_id=(chat_id)
      if chat_id.nil?
        fail ArgumentError, 'chat_id cannot be nil'
      end

      @chat_id = chat_id
    end

    # Custom attribute writer method with validation
    # @param [Object] from_me Value to be assigned
    def from_me=(from_me)
      if from_me.nil?
        fail ArgumentError, 'from_me cannot be nil'
      end

      @from_me = from_me
    end

    # Custom attribute writer method with validation
    # @param [Object] timestamp Value to be assigned
    def timestamp=(timestamp)
      if timestamp.nil?
        fail ArgumentError, 'timestamp cannot be nil'
      end

      @timestamp = timestamp
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          type == o.type &&
          subtype == o.subtype &&
          chat_id == o.chat_id &&
          chat_name == o.chat_name &&
          from == o.from &&
          from_me == o.from_me &&
          from_name == o.from_name &&
          source == o.source &&
          timestamp == o.timestamp &&
          device_id == o.device_id &&
          status == o.status &&
          text == o.text &&
          image == o.image &&
          video == o.video &&
          short == o.short &&
          gif == o.gif &&
          audio == o.audio &&
          voice == o.voice &&
          document == o.document &&
          link_preview == o.link_preview &&
          sticker == o.sticker &&
          location == o.location &&
          live_location == o.live_location &&
          contact == o.contact &&
          contact_list == o.contact_list &&
          interactive == o.interactive &&
          poll == o.poll &&
          hsm == o.hsm &&
          system == o.system &&
          order == o.order &&
          group_invite == o.group_invite &&
          newsletter_invite == o.newsletter_invite &&
          admin_invite == o.admin_invite &&
          product == o.product &&
          catalog == o.catalog &&
          product_items == o.product_items &&
          action == o.action &&
          context == o.context &&
          event == o.event &&
          list == o.list &&
          buttons == o.buttons &&
          reactions == o.reactions &&
          labels == o.labels
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, type, subtype, chat_id, chat_name, from, from_me, from_name, source, timestamp, device_id, status, text, image, video, short, gif, audio, voice, document, link_preview, sticker, location, live_location, contact, contact_list, interactive, poll, hsm, system, order, group_invite, newsletter_invite, admin_invite, product, catalog, product_items, action, context, event, list, buttons, reactions, labels].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
