=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module OpenapiClient
  class SenderAudio
    # Use the phone number or [Chat ID](https://support.whapi.cloud/help-desk/faq/chat-id.-what-is-it-and-how-to-get-it) of the contact/group/channel to which you want to send the message. Use [Get groups](https://whapi.readme.io/reference/getgroups) to get the group ID.
    attr_accessor :to

    # Message ID of the message to be quoted
    attr_accessor :quoted

    # Time in seconds for the message to be deleted. The Disappearing messages setting should be enabled in the chat where you are sending this message.
    attr_accessor :ephemeral

    # Message ID of the message to be edited
    attr_accessor :edit

    attr_accessor :media

    # Mime type of media
    attr_accessor :mime_type

    # Do not use our encoding
    attr_accessor :no_encode

    # Do not use the cache in a request
    attr_accessor :no_cache

    # Optional. For audio files, this field indicates the duration of the audio file in seconds.
    attr_accessor :seconds

    # Is view once
    attr_accessor :view_once

    # Background color of the story (ARGB)
    attr_accessor :background_color

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'to' => :'to',
        :'quoted' => :'quoted',
        :'ephemeral' => :'ephemeral',
        :'edit' => :'edit',
        :'media' => :'media',
        :'mime_type' => :'mime_type',
        :'no_encode' => :'no_encode',
        :'no_cache' => :'no_cache',
        :'seconds' => :'seconds',
        :'view_once' => :'view_once',
        :'background_color' => :'background_color'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'to' => :'String',
        :'quoted' => :'String',
        :'ephemeral' => :'Integer',
        :'edit' => :'String',
        :'media' => :'SendMediaMedia',
        :'mime_type' => :'String',
        :'no_encode' => :'Boolean',
        :'no_cache' => :'Boolean',
        :'seconds' => :'Integer',
        :'view_once' => :'Boolean',
        :'background_color' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'MessagePropsAudio',
      :'SendMedia',
      :'Sender',
      :'ViewOnce'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::SenderAudio` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::SenderAudio`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'to')
        self.to = attributes[:'to']
      else
        self.to = nil
      end

      if attributes.key?(:'quoted')
        self.quoted = attributes[:'quoted']
      end

      if attributes.key?(:'ephemeral')
        self.ephemeral = attributes[:'ephemeral']
      end

      if attributes.key?(:'edit')
        self.edit = attributes[:'edit']
      end

      if attributes.key?(:'media')
        self.media = attributes[:'media']
      else
        self.media = nil
      end

      if attributes.key?(:'mime_type')
        self.mime_type = attributes[:'mime_type']
      end

      if attributes.key?(:'no_encode')
        self.no_encode = attributes[:'no_encode']
      end

      if attributes.key?(:'no_cache')
        self.no_cache = attributes[:'no_cache']
      end

      if attributes.key?(:'seconds')
        self.seconds = attributes[:'seconds']
      end

      if attributes.key?(:'view_once')
        self.view_once = attributes[:'view_once']
      end

      if attributes.key?(:'background_color')
        self.background_color = attributes[:'background_color']
      else
        self.background_color = '#00000000'
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @to.nil?
        invalid_properties.push('invalid value for "to", to cannot be nil.')
      end

      pattern = Regexp.new(/^[\d-]{10,31}(@[\w\.]{1,})?$/)
      if @to !~ pattern
        invalid_properties.push("invalid value for \"to\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^[A-Za-z0-9._]{4,23}-[A-Za-z0-9._]{4,14}(-[A-Za-z0-9._]{4,10})?(-[A-Za-z0-9._]{4,10})?$/)
      if !@quoted.nil? && @quoted !~ pattern
        invalid_properties.push("invalid value for \"quoted\", must conform to the pattern #{pattern}.")
      end

      if !@ephemeral.nil? && @ephemeral > 604800
        invalid_properties.push('invalid value for "ephemeral", must be smaller than or equal to 604800.')
      end

      if !@ephemeral.nil? && @ephemeral < 1
        invalid_properties.push('invalid value for "ephemeral", must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^[A-Za-z0-9._]{4,23}-[A-Za-z0-9._]{4,14}(-[A-Za-z0-9._]{4,10})?(-[A-Za-z0-9._]{4,10})?$/)
      if !@edit.nil? && @edit !~ pattern
        invalid_properties.push("invalid value for \"edit\", must conform to the pattern #{pattern}.")
      end

      if @media.nil?
        invalid_properties.push('invalid value for "media", media cannot be nil.')
      end

      pattern = Regexp.new(/^#[0-9a-fA-F]{6,8}$/)
      if !@background_color.nil? && @background_color !~ pattern
        invalid_properties.push("invalid value for \"background_color\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @to.nil?
      return false if @to !~ Regexp.new(/^[\d-]{10,31}(@[\w\.]{1,})?$/)
      return false if !@quoted.nil? && @quoted !~ Regexp.new(/^[A-Za-z0-9._]{4,23}-[A-Za-z0-9._]{4,14}(-[A-Za-z0-9._]{4,10})?(-[A-Za-z0-9._]{4,10})?$/)
      return false if !@ephemeral.nil? && @ephemeral > 604800
      return false if !@ephemeral.nil? && @ephemeral < 1
      return false if !@edit.nil? && @edit !~ Regexp.new(/^[A-Za-z0-9._]{4,23}-[A-Za-z0-9._]{4,14}(-[A-Za-z0-9._]{4,10})?(-[A-Za-z0-9._]{4,10})?$/)
      return false if @media.nil?
      return false if !@background_color.nil? && @background_color !~ Regexp.new(/^#[0-9a-fA-F]{6,8}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] to Value to be assigned
    def to=(to)
      if to.nil?
        fail ArgumentError, 'to cannot be nil'
      end

      pattern = Regexp.new(/^[\d-]{10,31}(@[\w\.]{1,})?$/)
      if to !~ pattern
        fail ArgumentError, "invalid value for \"to\", must conform to the pattern #{pattern}."
      end

      @to = to
    end

    # Custom attribute writer method with validation
    # @param [Object] quoted Value to be assigned
    def quoted=(quoted)
      if quoted.nil?
        fail ArgumentError, 'quoted cannot be nil'
      end

      pattern = Regexp.new(/^[A-Za-z0-9._]{4,23}-[A-Za-z0-9._]{4,14}(-[A-Za-z0-9._]{4,10})?(-[A-Za-z0-9._]{4,10})?$/)
      if quoted !~ pattern
        fail ArgumentError, "invalid value for \"quoted\", must conform to the pattern #{pattern}."
      end

      @quoted = quoted
    end

    # Custom attribute writer method with validation
    # @param [Object] ephemeral Value to be assigned
    def ephemeral=(ephemeral)
      if ephemeral.nil?
        fail ArgumentError, 'ephemeral cannot be nil'
      end

      if ephemeral > 604800
        fail ArgumentError, 'invalid value for "ephemeral", must be smaller than or equal to 604800.'
      end

      if ephemeral < 1
        fail ArgumentError, 'invalid value for "ephemeral", must be greater than or equal to 1.'
      end

      @ephemeral = ephemeral
    end

    # Custom attribute writer method with validation
    # @param [Object] edit Value to be assigned
    def edit=(edit)
      if edit.nil?
        fail ArgumentError, 'edit cannot be nil'
      end

      pattern = Regexp.new(/^[A-Za-z0-9._]{4,23}-[A-Za-z0-9._]{4,14}(-[A-Za-z0-9._]{4,10})?(-[A-Za-z0-9._]{4,10})?$/)
      if edit !~ pattern
        fail ArgumentError, "invalid value for \"edit\", must conform to the pattern #{pattern}."
      end

      @edit = edit
    end

    # Custom attribute writer method with validation
    # @param [Object] media Value to be assigned
    def media=(media)
      if media.nil?
        fail ArgumentError, 'media cannot be nil'
      end

      @media = media
    end

    # Custom attribute writer method with validation
    # @param [Object] background_color Value to be assigned
    def background_color=(background_color)
      if background_color.nil?
        fail ArgumentError, 'background_color cannot be nil'
      end

      pattern = Regexp.new(/^#[0-9a-fA-F]{6,8}$/)
      if background_color !~ pattern
        fail ArgumentError, "invalid value for \"background_color\", must conform to the pattern #{pattern}."
      end

      @background_color = background_color
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          to == o.to &&
          quoted == o.quoted &&
          ephemeral == o.ephemeral &&
          edit == o.edit &&
          media == o.media &&
          mime_type == o.mime_type &&
          no_encode == o.no_encode &&
          no_cache == o.no_cache &&
          seconds == o.seconds &&
          view_once == o.view_once &&
          background_color == o.background_color
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [to, quoted, ephemeral, edit, media, mime_type, no_encode, no_cache, seconds, view_once, background_color].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
