=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module OpenapiClient
  class Settings
    # Backoff delay for a failed callback in milliseconds This setting is used to configure the amount of time the backoff delays before retrying a failed callback. The backoff delay increases linearly by this value each time a callback fails to get a HTTPS 200 OK response. The backoff delay is capped by the max_callback_backoff_delay_ms setting.
    attr_accessor :callback_backoff_delay_ms

    # Maximum delay for a failed callback in milliseconds
    attr_accessor :max_callback_backoff_delay_ms

    # Stores callbacks on disk until they are successfully acknowledged by the Webhook or not. Restart required.
    attr_accessor :callback_persist

    attr_accessor :media

    attr_accessor :webhooks

    # Use your Socks5 proxy if your account activity arouses suspicion from WhatsApp. This can help maintain anonymity and ensure smooth operation.
    attr_accessor :proxy

    # Service proxy for mobile authorization.
    attr_accessor :mobile_proxy

    # When true, API will not send online status to the server on connection. This will allow you to receive push notifications to devices connected to the number. Working after reconnect.
    attr_accessor :offline_mode

    # When true, all messages will be cached after the connection. If false, old messages will selectively not be cached, allowing large accounts to run faster. Working after reconnect.
    attr_accessor :full_history

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'callback_backoff_delay_ms' => :'callback_backoff_delay_ms',
        :'max_callback_backoff_delay_ms' => :'max_callback_backoff_delay_ms',
        :'callback_persist' => :'callback_persist',
        :'media' => :'media',
        :'webhooks' => :'webhooks',
        :'proxy' => :'proxy',
        :'mobile_proxy' => :'mobile_proxy',
        :'offline_mode' => :'offline_mode',
        :'full_history' => :'full_history'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'callback_backoff_delay_ms' => :'Float',
        :'max_callback_backoff_delay_ms' => :'Float',
        :'callback_persist' => :'Boolean',
        :'media' => :'MediaSettings',
        :'webhooks' => :'Array<Webhook>',
        :'proxy' => :'String',
        :'mobile_proxy' => :'String',
        :'offline_mode' => :'Boolean',
        :'full_history' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::Settings` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::Settings`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'callback_backoff_delay_ms')
        self.callback_backoff_delay_ms = attributes[:'callback_backoff_delay_ms']
      end

      if attributes.key?(:'max_callback_backoff_delay_ms')
        self.max_callback_backoff_delay_ms = attributes[:'max_callback_backoff_delay_ms']
      end

      if attributes.key?(:'callback_persist')
        self.callback_persist = attributes[:'callback_persist']
      end

      if attributes.key?(:'media')
        self.media = attributes[:'media']
      end

      if attributes.key?(:'webhooks')
        if (value = attributes[:'webhooks']).is_a?(Array)
          self.webhooks = value
        end
      end

      if attributes.key?(:'proxy')
        self.proxy = attributes[:'proxy']
      end

      if attributes.key?(:'mobile_proxy')
        self.mobile_proxy = attributes[:'mobile_proxy']
      end

      if attributes.key?(:'offline_mode')
        self.offline_mode = attributes[:'offline_mode']
      else
        self.offline_mode = false
      end

      if attributes.key?(:'full_history')
        self.full_history = attributes[:'full_history']
      else
        self.full_history = false
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@callback_backoff_delay_ms.nil? && @callback_backoff_delay_ms > 15000
        invalid_properties.push('invalid value for "callback_backoff_delay_ms", must be smaller than or equal to 15000.')
      end

      if !@callback_backoff_delay_ms.nil? && @callback_backoff_delay_ms < 3000
        invalid_properties.push('invalid value for "callback_backoff_delay_ms", must be greater than or equal to 3000.')
      end

      if !@max_callback_backoff_delay_ms.nil? && @max_callback_backoff_delay_ms > 3600000
        invalid_properties.push('invalid value for "max_callback_backoff_delay_ms", must be smaller than or equal to 3600000.')
      end

      if !@max_callback_backoff_delay_ms.nil? && @max_callback_backoff_delay_ms < 600000
        invalid_properties.push('invalid value for "max_callback_backoff_delay_ms", must be greater than or equal to 600000.')
      end

      pattern = Regexp.new(/^socks5h?:\/\/([!-\/:-@\[-`{-~a-zA-Z0-9_-]+):([a-zA-Z0-9_-]+)@(((?:[0-9]{1,3}\.){3}[0-9]{1,3})|[a-zA-Z0-9.]+):([0-9]{1,5})$|^$/)
      if !@proxy.nil? && @proxy !~ pattern
        invalid_properties.push("invalid value for \"proxy\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@callback_backoff_delay_ms.nil? && @callback_backoff_delay_ms > 15000
      return false if !@callback_backoff_delay_ms.nil? && @callback_backoff_delay_ms < 3000
      return false if !@max_callback_backoff_delay_ms.nil? && @max_callback_backoff_delay_ms > 3600000
      return false if !@max_callback_backoff_delay_ms.nil? && @max_callback_backoff_delay_ms < 600000
      return false if !@proxy.nil? && @proxy !~ Regexp.new(/^socks5h?:\/\/([!-\/:-@\[-`{-~a-zA-Z0-9_-]+):([a-zA-Z0-9_-]+)@(((?:[0-9]{1,3}\.){3}[0-9]{1,3})|[a-zA-Z0-9.]+):([0-9]{1,5})$|^$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] callback_backoff_delay_ms Value to be assigned
    def callback_backoff_delay_ms=(callback_backoff_delay_ms)
      if callback_backoff_delay_ms.nil?
        fail ArgumentError, 'callback_backoff_delay_ms cannot be nil'
      end

      if callback_backoff_delay_ms > 15000
        fail ArgumentError, 'invalid value for "callback_backoff_delay_ms", must be smaller than or equal to 15000.'
      end

      if callback_backoff_delay_ms < 3000
        fail ArgumentError, 'invalid value for "callback_backoff_delay_ms", must be greater than or equal to 3000.'
      end

      @callback_backoff_delay_ms = callback_backoff_delay_ms
    end

    # Custom attribute writer method with validation
    # @param [Object] max_callback_backoff_delay_ms Value to be assigned
    def max_callback_backoff_delay_ms=(max_callback_backoff_delay_ms)
      if max_callback_backoff_delay_ms.nil?
        fail ArgumentError, 'max_callback_backoff_delay_ms cannot be nil'
      end

      if max_callback_backoff_delay_ms > 3600000
        fail ArgumentError, 'invalid value for "max_callback_backoff_delay_ms", must be smaller than or equal to 3600000.'
      end

      if max_callback_backoff_delay_ms < 600000
        fail ArgumentError, 'invalid value for "max_callback_backoff_delay_ms", must be greater than or equal to 600000.'
      end

      @max_callback_backoff_delay_ms = max_callback_backoff_delay_ms
    end

    # Custom attribute writer method with validation
    # @param [Object] proxy Value to be assigned
    def proxy=(proxy)
      if proxy.nil?
        fail ArgumentError, 'proxy cannot be nil'
      end

      pattern = Regexp.new(/^socks5h?:\/\/([!-\/:-@\[-`{-~a-zA-Z0-9_-]+):([a-zA-Z0-9_-]+)@(((?:[0-9]{1,3}\.){3}[0-9]{1,3})|[a-zA-Z0-9.]+):([0-9]{1,5})$|^$/)
      if proxy !~ pattern
        fail ArgumentError, "invalid value for \"proxy\", must conform to the pattern #{pattern}."
      end

      @proxy = proxy
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          callback_backoff_delay_ms == o.callback_backoff_delay_ms &&
          max_callback_backoff_delay_ms == o.max_callback_backoff_delay_ms &&
          callback_persist == o.callback_persist &&
          media == o.media &&
          webhooks == o.webhooks &&
          proxy == o.proxy &&
          mobile_proxy == o.mobile_proxy &&
          offline_mode == o.offline_mode &&
          full_history == o.full_history
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [callback_backoff_delay_ms, max_callback_backoff_delay_ms, callback_persist, media, webhooks, proxy, mobile_proxy, offline_mode, full_history].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
