=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module OpenapiClient
  class StatusEnum
    FAILED = "failed".freeze
    PENDING = "pending".freeze
    SENT = "sent".freeze
    DELIVERED = "delivered".freeze
    READ = "read".freeze
    PLAYED = "played".freeze
    DELETED = "deleted".freeze

    def self.all_vars
      @all_vars ||= [FAILED, PENDING, SENT, DELIVERED, READ, PLAYED, DELETED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if StatusEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #StatusEnum"
    end
  end
end
