=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::BusinessApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BusinessApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::BusinessApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BusinessApi' do
    it 'should create an instance of BusinessApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::BusinessApi)
    end
  end

  # unit tests for create_collection
  # Create collection
  # Create business collection
  # @param business_collection_create Business collection parameters
  # @param [Hash] opts the optional parameters
  # @return [BusinessCollectionEditResult]
  describe 'create_collection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_product
  # Create product
  # In this method you will be able to register a product in your catalog
  # @param [Hash] opts the optional parameters
  # @option opts [ProductCreate] :product_create Request body
  # @return [Product]
  describe 'create_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_collection
  # Delete collection
  # Method to delete business collection
  # @param collection_id Collection ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'delete_collection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_product
  # Delete product
  # In this method you will be able to delete a product by its ID
  # @param product_id Product ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'delete_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_business_profile
  # Edit your Business Profile
  # The method allows you to edit information of your WhatsApp Business profile
  # @param [Hash] opts the optional parameters
  # @option opts [BusinessProfileCustom] :business_profile_custom Request body
  # @return [ResponseSuccess]
  describe 'edit_business_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_collection
  # Edit collection
  # With this method you will be able to edit business collection
  # @param collection_id Collection ID
  # @param business_collection_edit Business collection edit parameters
  # @param [Hash] opts the optional parameters
  # @return [BusinessCollectionEditResult]
  describe 'edit_collection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_profile
  # Get business profile
  # The method allows you to get information about your WhatsApp Business profile
  # @param [Hash] opts the optional parameters
  # @return [BusinessProfile]
  describe 'get_business_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_collection
  # Get collection
  # With this method you will be able to get business collection
  # @param collection_id Collection ID
  # @param [Hash] opts the optional parameters
  # @return [BusinessCollection]
  describe 'get_collection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_collections_list
  # Get collections
  # With this method you will be able to get the collections list from a Whatsapp Business catalog
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count Count of objects to return
  # @option opts [Float] :offset Offset of objects to return
  # @return [BusinessCollectionList]
  describe 'get_collections_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_contact_products
  # Get products by Contact ID
  # This method allows you to get the catalog and products by [Chat ID](https://support.whapi.cloud/help-desk/faq/chat-id.-what-is-it-and-how-to-get-it), even if it is not in your contact list
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count Count of objects to return
  # @option opts [Float] :offset Offset of objects to return
  # @return [ProductsList]
  describe 'get_contact_products test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_order_items
  # Get order items
  # The method allows you to get information about the items in the shopping cart sent to you in messages. Note! Use the token as a Query (as in a get request). [More details in the knowledge base](https://support.whapi.cloud/help-desk/receiving/http-api/get-order-items)
  # @param order_id Order ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order_token Base64 token from order for receiving information
  # @return [OrderItems]
  describe 'get_order_items test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_product
  # Get product
  # In this method you will be able to get your product by its ID
  # @param product_id Product ID
  # @param [Hash] opts the optional parameters
  # @return [Product]
  describe 'get_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_products
  # Get products
  # With this method you will be able to get the products from a Whatsapp Business catalog
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count Count of objects to return
  # @option opts [Float] :offset Offset of objects to return
  # @return [ProductsList]
  describe 'get_products test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_catalog
  # Send catalog by Contact ID (phone number)
  # @param contact_id Contact ID
  # @param sender_catalog_by_id Message catalog
  # @param [Hash] opts the optional parameters
  # @return [SentMessage]
  describe 'send_catalog test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_product
  # Send product
  # The method is for sending an item from your catalog
  # @param product_id Product ID
  # @param sender_product_from_catalog Message product
  # @param [Hash] opts the optional parameters
  # @return [SentMessage]
  describe 'send_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_product
  # Update product
  # The *images* field is required and must contain all images
  # @param product_id Product ID
  # @param product_edit Message product
  # @param [Hash] opts the optional parameters
  # @return [Product]
  describe 'update_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
