=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ChatsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ChatsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ChatsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChatsApi' do
    it 'should create an instance of ChatsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ChatsApi)
    end
  end

  # unit tests for archive_chat
  # 🗄 Archive/Unarchive chat
  # This method is responsible for archiving or unarchiving chats
  # @param chat_id Chat ID
  # @param [Hash] opts the optional parameters
  # @option opts [ArchiveChatRequest] :archive_chat_request Request body
  # @return [ResponseSuccess]
  describe 'archive_chat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_chat
  # ❌ Delete chat
  # This method is responsible for deleting chats
  # @param chat_id Chat ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'delete_chat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_chat
  # Get chat
  # This method is responsible for returning the metadata of a chat. Read more about [Chat ID](https://support.whapi.cloud/help-desk/faq/chat-id.-what-is-it-and-how-to-get-it)
  # @param chat_id Chat ID
  # @param [Hash] opts the optional parameters
  # @return [Chat]
  describe 'get_chat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_chats
  # Get chats
  # This method is responsible for returning all of your chats. If you need to get a profile pic of your contacts or chats, [refer to these instructions](https://support.whapi.cloud/help-desk/receiving/http-api/get-a-profile-picture-of-a-chat-or-user).
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count Count of objects to return
  # @option opts [Float] :offset Offset of objects to return
  # @return [ChatsList]
  describe 'get_chats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_chat
  # ⚙️Chat Settings Management: Pin, Mute, Read, Disappearing.
  # This method is responsible for pinning and unpinning, for muting and unmuting your chats. Also this method is responsible for performing the action of reading an entire chat or marking a chat as unread
  # @param chat_id Chat ID
  # @param [Hash] opts the optional parameters
  # @option opts [PatchChatRequest] :patch_chat_request Request body
  # @return [ResponseSuccess]
  describe 'patch_chat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
