=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CommunitiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CommunitiesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CommunitiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunitiesApi' do
    it 'should create an instance of CommunitiesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CommunitiesApi)
    end
  end

  # unit tests for add_community_participant
  # Add participants to community
  # This method is responsible for add participants community.
  # @param community_id Community ID
  # @param list_participants_request 
  # @param [Hash] opts the optional parameters
  # @return [ResponseListParticipants]
  describe 'add_community_participant test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for change_community_settings
  # Change community settings
  # This method is responsible for change a community settings.
  # @param community_id Community ID
  # @param change_community_settings_request Community change settings data
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'change_community_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_community
  # Create community
  # This method is responsible for creating a community. [Learn more about the nuances of community:](https://support.whapi.cloud/help-desk/communities/introduction)
  # @param create_community_request Community data
  # @param [Hash] opts the optional parameters
  # @return [Group]
  describe 'create_community test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_group_in_community
  # Create group in community
  # This method is responsible for creating a group in community. [Learn more about the nuances of community:](https://support.whapi.cloud/help-desk/communities/introduction)
  # @param community_id Community ID
  # @param create_group_in_community_request Group data
  # @param [Hash] opts the optional parameters
  # @return [Group]
  describe 'create_group_in_community test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for deactivate_community
  # Deactivate community
  # This method is responsible for deactivate community.
  # @param community_id Community ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'deactivate_community test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for demote_community_participant
  # Demote participants to admin in community
  # This method is responsible for demote participants to admin in community.
  # @param community_id Community ID
  # @param list_participants_request 
  # @param [Hash] opts the optional parameters
  # @return [ResponseListParticipants]
  describe 'demote_community_participant test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_communities
  # Get communities
  # This method is responsible for get a communities. [Learn more about the nuances of community:](https://support.whapi.cloud/help-desk/communities/introduction)
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count Count of objects to return
  # @option opts [Float] :offset Offset of objects to return
  # @return [GroupsList]
  describe 'get_communities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_community
  # Get community
  # This method is responsible for get a community. [Learn more about the nuances of community:](https://support.whapi.cloud/help-desk/communities/introduction)
  # @param community_id Community ID
  # @param [Hash] opts the optional parameters
  # @return [Group]
  describe 'get_community test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_community_sub_groups
  # Get community subgroups
  # This method is responsible for get a community subgroups. [Learn more about the nuances of community:](https://support.whapi.cloud/help-desk/communities/introduction)
  # @param community_id Community ID
  # @param [Hash] opts the optional parameters
  # @return [CommunitySubGroups]
  describe 'get_community_sub_groups test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for join_in_community_group
  # Join in community group
  # This method is responsible for join in community group. [Learn more about the nuances of community:](https://support.whapi.cloud/help-desk/communities/introduction)
  # @param community_id Community ID
  # @param group_id Group ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'join_in_community_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for link_group_to_community
  # Link group to community
  # This method is responsible for link group to community.
  # @param community_id Community ID
  # @param group_id Group ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'link_group_to_community test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for promote_community_participant
  # Promote participants to admin in community
  # This method is responsible for promote participants to admin in community.
  # @param community_id Community ID
  # @param list_participants_request 
  # @param [Hash] opts the optional parameters
  # @return [ResponseListParticipants]
  describe 'promote_community_participant test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_community_participant
  # Remove participants from community
  # This method is responsible for remove paricipants from community.
  # @param community_id Community ID
  # @param list_participants_request 
  # @param [Hash] opts the optional parameters
  # @return [ResponseListParticipants]
  describe 'remove_community_participant test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_community_invite
  # Revoke community invite code
  # @param community_id Community ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'revoke_community_invite test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unlink_group_from_community
  # Unlink group from community
  # This method is responsible for unlink group from community.
  # @param community_id Community ID
  # @param group_id Group ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'unlink_group_from_community test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
