=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ContactsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContactsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ContactsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactsApi' do
    it 'should create an instance of ContactsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ContactsApi)
    end
  end

  # unit tests for check_exist
  # Check exist
  # The method individually checks for a number in WhatsApp without additional information
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'check_exist test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for check_phones
  # Check phones
  # This method returns whether or not the number has Whatsapp. Batch check provisioning is supported, and there is no batch check limit. However, an atypical mass check can draw attention to your number, so we advise [balancing the check between channels](https://support.whapi.cloud/help-desk/faq/checking-if-the-number-has-whatsapp)
  # @param check_contact_request Contact data
  # @param [Hash] opts the optional parameters
  # @return [CheckContactResponse]
  describe 'check_phones test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_contact
  # Get contact
  # This method is responsible for returning all of you contact’s metadata
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @return [Contact]
  describe 'get_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_contact_profile
  # Get profile
  # This method allows you to get profile information (description, profile image) by phone number, even if it is not in your contact list
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @return [UserProfile]
  describe 'get_contact_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_contacts
  # Get contacts
  # This method is responsible for returning all of your Whatsapp contacts
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count Count of objects to return
  # @option opts [Float] :offset Offset of objects to return
  # @return [ContactsList]
  describe 'get_contacts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_contact
  # Send contact
  # @param contact_id Contact ID
  # @param sender_contact_from_phonebook Message contact
  # @param [Hash] opts the optional parameters
  # @return [SentMessage]
  describe 'send_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
