=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::NewslettersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NewslettersApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::NewslettersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NewslettersApi' do
    it 'should create an instance of NewslettersApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::NewslettersApi)
    end
  end

  # unit tests for accept_newsletter_admin_request
  # Accept Newsletter admin-request
  # This method is responsible for accepting an request to become an administrator of a WhatsApp Channel. This request is a message that you can both send like invitation and receive through the received message webhook
  # @param newsletter_id Newsletter ID
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'accept_newsletter_admin_request test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_newsletter
  # Create newsletter
  # This method is responsible for creating a WhatsApp Channel. [How to send a post to WhatsApp Channel](https://support.whapi.cloud/help-desk/channels/send-post-to-whatsapp-channel)
  # @param create_newsletter_request Newsletter data
  # @param [Hash] opts the optional parameters
  # @return [Newsletter]
  describe 'create_newsletter test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_newsletter_admin_invite
  # Create Newsletter admin-invite
  # This method is responsible for sending an invitation for WhatsApp Channel administrator. Once the invitation is created, an invitation message will be sent to the contact
  # @param newsletter_id Newsletter ID
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateNewsletterAdminInviteRequest] :create_newsletter_admin_invite_request Invite data
  # @return [SentMessage]
  describe 'create_newsletter_admin_invite test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_newsletter
  # Delete newsletter
  # This method is responsible for deleting a WhatsApp Channel
  # @param newsletter_id Newsletter ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'delete_newsletter test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for demote_newsletter_admin
  # Demote Newsletter admin
  # This method is responsible for removing a user from the administration of the WhatsApp Channel
  # @param newsletter_id Newsletter ID
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'demote_newsletter_admin test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_newsletter
  # Edit newsletter
  # This method is responsible for editing a WhatsApp Newsletter Channel
  # @param newsletter_id Newsletter ID
  # @param edit_newsletter_request Newsletter data
  # @param [Hash] opts the optional parameters
  # @return [Newsletter]
  describe 'edit_newsletter test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for find_newsletter
  # Find newsletters by filters
  # This method returns a list of WhatsApp Channels data based on the search performed using filters provided in the request body
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country_code Country for search
  # @option opts [String] :search Search word
  # @option opts [String] :newsletter_field Cursor to continue pagination
  # @option opts [String] :cursor Cursor to continue pagination
  # @option opts [Float] :count Count of objects to return
  # @option opts [String] :sort Order for items in request
  # @return [NewslettersListPaged]
  describe 'find_newsletter test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_messages_newsletter
  # Get newsletter messages
  # The method returns the history of WhatsApp Channel messages
  # @param newsletter_id Newsletter ID
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count Count of objects to return
  # @option opts [Float] :before Request messages before the specified one (see first and last)
  # @option opts [Float] :after Request messages after the specified one (see first and last)
  # @return [MessagesList]
  describe 'get_messages_newsletter test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_newsletter
  # Get newsletter information
  # This method returns the metadata of a WhatsApp Channel
  # @param newsletter_id Newsletter ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_role User&#39;s role regarding the newsletter
  # @return [MessagesList]
  describe 'get_newsletter test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_newsletter_by_invite_code
  # Get newsletter info by invite code
  # @param newsletter_invite_code Newsletter Invite Code
  # @param [Hash] opts the optional parameters
  # @return [Newsletter]
  describe 'get_newsletter_by_invite_code test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_newsletters
  # Get newsletters
  # This method returns a list with metadata of your own WhatsApp Channel and followed Channels, including all Channel information and their views.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count Count of objects to return
  # @option opts [Float] :offset Offset of objects to return
  # @return [NewslettersList]
  describe 'get_newsletters test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for recommended_newsletter
  # Get recommended newsletters by country
  # This method returns a list of WhatsApp Channels data based on the search performed using filters provided in the request body
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country_code Country for search
  # @option opts [String] :cursor Cursor to continue pagination
  # @option opts [Float] :count Count of objects to return
  # @return [NewslettersListPaged]
  describe 'recommended_newsletter test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_newsletter_admin_invite
  # Revoke Newsletter admin-invite
  # This method is responsible for revoking an invitation for WhatsApp Channel administrator.
  # @param newsletter_id Newsletter ID
  # @param contact_id Contact ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'revoke_newsletter_admin_invite test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_newsletter_invite
  # Send newsletter invite link
  # @param newsletter_invite_code Newsletter Invite Code
  # @param sender_newsletter_invite_by_code Newsletter invite link
  # @param [Hash] opts the optional parameters
  # @return [SentMessage]
  describe 'send_newsletter_invite test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for subscribe_newsletter
  # Subscribe to newsletter
  # This method is responsible for following a WhatsApp Channel
  # @param newsletter_id Newsletter ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'subscribe_newsletter test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for subscribe_newsletter_invite
  # Subscribe to newsletter by invite code
  # This method is responsible for following a WhatsApp Channel
  # @param newsletter_invite_code Newsletter Invite Code
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'subscribe_newsletter_invite test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tracking_newsletter
  # Subscribe to newsletter updates
  # It is necessary to receive notifications about new votes in the polls
  # @param newsletter_id Newsletter ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'tracking_newsletter test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unsubscribe_newsletter
  # Unsubscribe from newsletter
  # This method is responsible for unfollowing a WhatsApp Channel
  # @param newsletter_id Newsletter ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'unsubscribe_newsletter test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unsubscribe_newsletter_invite
  # Unsubscribe from newsletter by invite code
  # This method is responsible for unfollowing a WhatsApp Channel
  # @param newsletter_invite_code Newsletter Invite Code
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'unsubscribe_newsletter_invite test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
