=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PresencesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PresencesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PresencesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PresencesApi' do
    it 'should create an instance of PresencesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PresencesApi)
    end
  end

  # unit tests for get_presence
  # Get presence
  # @param entry_id Contact or group id
  # @param [Hash] opts the optional parameters
  # @return [Presence]
  describe 'get_presence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_me_presence
  # Send online or offline presence
  # @param [Hash] opts the optional parameters
  # @option opts [SendMePresenceRequest] :send_me_presence_request 
  # @return [CheckContactResponse]
  describe 'send_me_presence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_presence
  # Send typing or recording presence
  # @param entry_id Contact or group id
  # @param [Hash] opts the optional parameters
  # @option opts [SendPresenceRequest] :send_presence_request 
  # @return [CheckContactResponse]
  describe 'send_presence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for subscribe_presence
  # Subscribe to presence
  # @param entry_id Contact or group id
  # @param [Hash] opts the optional parameters
  # @return [CheckContactResponse]
  describe 'subscribe_presence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
