=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::StatusesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StatusesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::StatusesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatusesApi' do
    it 'should create an instance of StatusesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::StatusesApi)
    end
  end

  # unit tests for get_message_view_statuses
  # Get message or story view statuses
  # @param message_id Message ID
  # @param [Hash] opts the optional parameters
  # @return [StatusesList]
  describe 'get_message_view_statuses test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
