=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::StoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StoriesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::StoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StoriesApi' do
    it 'should create an instance of StoriesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::StoriesApi)
    end
  end

  # unit tests for copy_story
  # Copy story
  # @param message_id Message ID
  # @param copy_stories Stories post parameters
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'copy_story test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_story
  # Create &amp; publish story
  # The method responsible for sending images or texts to your status. Remember that statuses disappear after 24 hours. The requirements for [sending all media types are identical](https://support.whapi.cloud/help-desk/sending/send-video-audio-image-document)
  # @param sender_stories Stories post parameters
  # @param [Hash] opts the optional parameters
  # @return [SentMessage]
  describe 'create_story test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_story_audio
  # 🎵️ Post audio story
  # The method responsible for sending audio to your status. Remember that statuses disappear after 24 hours. The requirements for [sending all media types are identical](https://support.whapi.cloud/help-desk/sending/send-video-audio-image-document)
  # @param sender_stories_audio Stories post parameters for audio
  # @param [Hash] opts the optional parameters
  # @return [SentMessage]
  describe 'create_story_audio test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_story_media
  # 🖼 Post media story
  # The method responsible for sending images or video to your status. Remember that statuses disappear after 24 hours. The requirements for [sending all media types are identical](https://support.whapi.cloud/help-desk/sending/send-video-audio-image-document)
  # @param media 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :mime_type Mime type of media
  # @option opts [Boolean] :no_encode Do not use our encoding
  # @option opts [Boolean] :no_cache Do not use the cache in a request
  # @option opts [String] :caption Optional. Text caption under the media.
  # @option opts [String] :preview Optional. Base64 encoded preview of the media. In JPEG format.
  # @option opts [Integer] :width Width of the media in pixels
  # @option opts [Integer] :height Height of the media in pixels
  # @option opts [Array<String>] :contacts List of contacts to send the story to
  # @option opts [Array<String>] :exclude_contacts List of contacts to exclude
  # @option opts [Boolean] :experimental Some untested improvements
  # @return [SentMessage]
  describe 'create_story_media test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_story_text
  # 💬 Post text story
  # The method responsible for sending texts to your status. Remember that statuses disappear after 24 hours.
  # @param sender_stories_text Text stories post parameters
  # @param [Hash] opts the optional parameters
  # @return [SentMessage]
  describe 'create_story_text test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_story
  # Delete story
  # @param message_id Message ID
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'delete_story test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_stories
  # Get list of stories
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :count Count of objects to return
  # @option opts [Float] :offset Offset of objects to return
  # @option opts [Float] :time_from Timestamp from which to get objects
  # @option opts [Float] :time_to Timestamp up to which to get objects
  # @option opts [Boolean] :normal_types If false, include system messages
  # @option opts [String] :author To filter by author (Contact ID)
  # @option opts [Boolean] :from_me If true, only return messages sent by the authenticated user. If false, only return messages sent by other users.
  # @return [MessagesList]
  describe 'get_stories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_story
  # Get story
  # @param message_id Message ID
  # @param [Hash] opts the optional parameters
  # @return [Message]
  describe 'get_story test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_message_story_text
  # 💬 Send story text message
  # The method responsible for sending texts to your status. Remember that statuses disappear after 24 hours.
  # @param sender_stories_text Text stories post parameters
  # @param [Hash] opts the optional parameters
  # @return [SentMessage]
  describe 'send_message_story_text test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
