=begin
#Whapi API

#Sending and receiving messages using HTTP requests. Fixed price with no hidden fees, without limits and restrictions. You will be able to send and receive text/media/files/locations/goods/orders/polls messages via WhatsApp in private or group chats. Guides and SDK can be found on our website.

The version of the OpenAPI document: 1.8.7
Contact: care@whapi.cloud
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::UsersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::UsersApi)
    end
  end

  # unit tests for get_user_profile
  # User info
  # The method allows you to get information about your WhatsApp profile
  # @param [Hash] opts the optional parameters
  # @return [UserProfile]
  describe 'get_user_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for login_user
  # Login user with QR-base64
  # This method returns an image of the type base64. You can render this in a component of the type image that is compatible with the language that you use to program. Just like on WhatsApp Web you will need to read a QR code to connect to Whapi.Cloud. There are two ways that you can do the reading of the QR code. Connect through our dashboard panel or Make this experience available within your own application.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :wakeup If set to false, the channel will not launch
  # @option opts [Float] :size Size of QR-code
  # @option opts [Float] :width Width of result image
  # @option opts [Float] :height Height of result image
  # @option opts [String] :color_light Background color
  # @option opts [String] :color_dark Color of code
  # @return [QR]
  describe 'login_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for login_user_image
  # Login user with QR-image
  # This method returns an image. Just like on WhatsApp Web you will need to read a QR code to connect to Whapi.Cloud. There are two ways that you can do the reading of the QR code. Connect through our dashboard panel or Make this experience available within your own application.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :wakeup If set to false, the channel will not launch
  # @option opts [Float] :size Size of QR-code
  # @option opts [Float] :width Width of result image
  # @option opts [Float] :height Height of result image
  # @option opts [String] :color_light Background color
  # @option opts [String] :color_dark Color of code
  # @return [File]
  describe 'login_user_image test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for login_user_row_data
  # Login user with QR-rowdata
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :wakeup If set to false, the channel will not launch
  # @return [QR]
  describe 'login_user_row_data test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for login_user_via_auth_code
  # Get auth code by phone number
  # This method returns a code that allows you to connect the phone number to the API without the need to scan a QR code, simply by entering the generated code.
  # @param phone_number Phone number without + and spaces, only digits
  # @param [Hash] opts the optional parameters
  # @return [AuthCode]
  describe 'login_user_via_auth_code test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for login_user_via_mobile
  # Login in whatsapp with phone number
  # Allows you to register a number on WhatsApp. Requires mandatory use of mobile proxies!
  # @param request_mobile_login Request body for login mobile
  # @param [Hash] opts the optional parameters
  # @return [MobileLoginStatus]
  describe 'login_user_via_mobile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for logout_user
  # Logout user
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'logout_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_user_profile
  # Update user info
  # This method is responsible for changing the details of your WhatsApp profile
  # @param user_profile_update Change user profile
  # @param [Hash] opts the optional parameters
  # @return [ResponseSuccess]
  describe 'update_user_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
